---
- name: Install HANA DB
  async: 1000
  poll: 0
  ansible.builtin.shell: |
    cat {{ usr_sap_path }}/hdblcm.xml | "{{ usr_sap_path }}/hana_setup/DATA_UNITS/SAP HANA DATABASE 2.0 FOR B1/LINX64SUSE/SAP_HANA_DATABASE/hdblcm" --ignore=check_signature_file --read_password_from_stdin=xml --configfile={{ usr_sap_path }}/hdblcm.cfg -b
  register: hana_db_install

- name: Wait for HANA DB installation to complete
  ansible.builtin.async_status:
    jid: "{{ hana_db_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 300
  delay: 30
  ignore_errors: True
  changed_when: "'already in use' not in job_result.stderr"

- name: Clean async job cache
  ansible.builtin.async_status:
    jid: "{{ hana_db_install.ansible_job_id }}"
    mode: cleanup

- name: Wait 2 mins for HANA DB to start
  pause:
    seconds: 120
  