---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: SLES15SP3
    tags:
      Name: sap-b1-ansible-molecule
      ansible_group: sap_hana_db
    image_owner: '231639157514'
    image_name: 'packer-aws-suse-15-sp3-20220706144824'
    instance_type: r5.xlarge
    vpc_subnet_id: 'subnet-011c84f0aa1ff4f27'
    region: eu-west-2
    security_groups:
      - eu-west-2-cutover-test-sg-20220314182735604900000003
    ssh_user: ec2-user
    assign_public_ip: False
    volumes:
      - device_name: /dev/sda1
        ebs:
          delete_on_termination: True
          volume_size: 20
          volume_type: gp3
      - device_name: /dev/sdh
        ebs:
          delete_on_termination: True
          volume_size: 100
          volume_type: gp3
          iops: 3000
          throughput: 125
      - device_name: /dev/sdi
        ebs:
          delete_on_termination: True
          volume_size: 100
          volume_type: gp3
          iops: 3000
          throughput: 125
      - device_name: /dev/sdj
        ebs:
          delete_on_termination: True
          volume_size: 100
          volume_type: gp3
          iops: 3000
          throughput: 125
      - device_name: /dev/sdk
        ebs:
          delete_on_termination: True
          volume_size: 100
          volume_type: gp3
          iops: 3000
          throughput: 125
    connection_options:
      # ansible_connection: aws_ssm
      # ansible_aws_ssm_bucket_name: /ansible/ssm/bucket
      # ansible_aws_ssm_region: /ansible/ssm/region
      ansible_connection: community.aws.aws_ssm
      ansible_aws_ssm_bucket_name: "{{ lookup('amazon.aws.ssm_parameter', '/ansible/ssm/bucket') }}"
      ansible_aws_ssm_region: "{{ lookup('amazon.aws.ssm_parameter', '/ansible/ssm/region') }}"

provisioner:
  name: ansible

verifier:
  name: ansible
